package com.example.hmattendance.models;

public class Attendance {
    private int id; // Primary key, auto-generated by DB
    private String date;
    private String studentId;
    private String status; // e.g., "Present", "Absent", "Late", "Excused"
    private String clubName; // To link attendance to a specific club
    private String timestamp; // Optional: when the record was created/updated

    // Constructor for creating new attendance records (ID will be auto-generated)
    public Attendance(String date, String studentId, String status, String clubName, String timestamp) {
        this.date = date;
        this.studentId = studentId;
        this.status = status;
        this.clubName = clubName;
        this.timestamp = timestamp;
    }

    // Constructor for retrieving attendance records from DB (includes ID)
    public Attendance(int id, String date, String studentId, String status, String clubName, String timestamp) {
        this.id = id;
        this.date = date;
        this.studentId = studentId;
        this.status = status;
        this.clubName = clubName;
        this.timestamp = timestamp;
    }

    // Getters
    public int getId() { return id; }
    public String getDate() { return date; }
    public String getStudentId() { return studentId; }
    public String getStatus() { return status; }
    public String getClubName() { return clubName; }
    public String getTimestamp() { return timestamp; }

    // Setters (useful for updates or setting ID after insertion)
    public void setId(int id) { this.id = id; }
    public void setDate(String date) { this.date = date; }
    public void setStudentId(String studentId) { this.studentId = studentId; }
    public void setStatus(String status) { this.status = status; }
    public void setClubName(String clubName) { this.clubName = clubName; }
    public void setTimestamp(String timestamp) { this.timestamp = timestamp; }
}